version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /docker/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host
  hass-configurator:
    container_name: configurator
    image: causticlab/hass-configurator-docker:latest
    volumes:
      - /docker/hass-configurator:/config
      - /docker/home-assistant:/hass-config
    restart: always
    ports:
      - "3218:3218/tcp"
