version: '3'
 
services:
  homeassistant:
    container_name: homeassistant
    restart: unless-stopped
    environment:
      TZ: Atlantic/Canary
    volumes:
      - '${HOME_FOLDER}/config:/config'
    ports:
      - '8123:8123'
    depends_on:
      - homeassistant_db
    image: homeassistant/home-assistant:latest
 
  homeassistant_db:
    container_name: homeassistant_db
    restart: unless-stopped
    environment:
      TZ: Atlantic/Canary
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: homeassistant
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - './mariadb:/var/lib/mysql'
    image: mariadb:latest