version: '2'

services:
    filebrowser:
        container_name: filebrowser
        restart: unless-stopped
        volumes:
            - '~/docker/:/srv'
            - '~/docker/filebrowser/database.db:/database.db'
        ports:
            - '8200:80'
        image: filebrowser/filebrowser