version: '3'

services:
  esphome:
    container_name: esphome
    restart: unless-stopped
    volumes:
      - '${HOME_FOLDER}/docker/esphome/config:/config'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '6052:6052'
    image: esphome/esphome
    network_mode: host
